"""create_activity model

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-22 17:38:30.263491
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_media',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filepath', sa.String(length=512), nullable=False),
    sa.Column('media_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_alerts',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('activity_media_id', sa.Uuid(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('timestamp', sa.Float(), nullable=False),
    sa.Column('bbox', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('snapshot_path', sa.String(length=512), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_media_id'], ['activity_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_configs',
    sa.Column('tenant_id', sa.Uuid(), nullable=False),
    sa.Column('activity_media_id', sa.Uuid(), nullable=False),
    sa.Column('polygon_points', sa.JSON(), nullable=True),
    sa.Column('detect_fall', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('detect_aggression', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('detect_intrusion', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('detect_loitering', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('loitering_threshold', sa.Float(), server_default='15.0', nullable=False),
    sa.Column('detect_occupancy', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('occupancy_limit', sa.Integer(), server_default='5', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('is_delete', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('update_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_media_id'], ['activity_media.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activity_configs')
    op.drop_table('activity_alerts')
    op.drop_table('activity_media')
    # ### end Alembic commands ###
