"""add_crop_path_to_person_occurrences

Revision ID: 0006
Revises: 0005
Create Date: 2026-06-18 13:18:34.269631
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0006'
down_revision = '0005'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_occurrences', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crop_path', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person_occurrences', schema=None) as batch_op:
        batch_op.drop_column('crop_path')

    # ### end Alembic commands ###
