"""add_attendance_timestamps

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-19 06:51:29.465229
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_attendance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_entry_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.add_column(sa.Column('employee_exit_timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_attendance_logs', schema=None) as batch_op:
        batch_op.alter_column('session_id',
               existing_type=sa.UUID(),
               nullable=False)
        batch_op.drop_column('employee_exit_timestamp')
        batch_op.drop_column('employee_entry_timestamp')

    # ### end Alembic commands ###
