"""add_sleeping_walking_to_activity_config

Revision ID: 0007
Revises: 0006
Create Date: 2026-06-23 11:56:45.533604
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0007'
down_revision = '0006'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('detect_sleeping', sa.Boolean(), server_default='true', nullable=False))
        batch_op.add_column(sa.Column('detect_walking', sa.Boolean(), server_default='true', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.drop_column('detect_walking')
        batch_op.drop_column('detect_sleeping')

    # ### end Alembic commands ###
