"""add_employee_visitor_counts_to_session

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-26 06:39:41.335705
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_analytics_sessions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('employee_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('visitor_count', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('people_analytics_sessions', schema=None) as batch_op:
        batch_op.drop_column('visitor_count')
        batch_op.drop_column('employee_count')

    # ### end Alembic commands ###
