"""add_activity_selected_labels_and_output

Revision ID: 0009
Revises: 0008
Create Date: 2026-06-26 10:12:28.108548
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0009'
down_revision = '0008'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('selected_activities', sa.JSON(), nullable=True))

    with op.batch_alter_table('activity_media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('output_filepath', sa.String(length=512), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('activity_media', schema=None) as batch_op:
        batch_op.drop_column('output_filepath')

    with op.batch_alter_table('activity_configs', schema=None) as batch_op:
        batch_op.drop_column('selected_activities')

    # ### end Alembic commands ###
